---
go_tarball: "go1.8.1.linux-amd64.tar.gz"
go_tarball_checksum: "sha256:a579ab19d5237e263254f1eac5352efcf1d70b9dacadb6d6bb12b0911ede8994"
go_version_target: "go version go1.8.1 linux/amd64"
set_go_path: true
