---
- name: create config file
  become: yes
  become_method: sudo
  template:
    src: pilosa.cfg.j2
    dest: /etc/pilosa.cfg
    owner: root
    group: root
    mode: 0644
    force: yes
- name: add pilosa service
  become: yes
  become_method: sudo
  template:
    src: pilosa.service.j2
    dest: /etc/systemd/system/pilosa.service
    owner: root
    group: root
    mode: 0644
    force: yes
- name: start pilosa service
  become: yes
  become_method: sudo
  systemd:
    daemon_reload: yes
    enabled: yes
    state: started
    name: pilosa.service
