---
- name: common tasks
  import_playbook: common.yml
- name: basics
  hosts: agent
  gather_facts: yes
  tasks:
    - name: install software apt
      become: yes
      become_method: sudo
      when: ansible_distribution == "Ubuntu"
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
          - make
          - git
          - htop
          - jq
          - unzip
          - gcc
          - libssl-dev
          - libffi-dev
    - name: install software yum
      become: yes
      become_method: sudo
      when: ansible_distribution == "OracleLinux" or ansible_distribution == "Amazon" or ansible_distribution == "CentOS"
      yum:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
          - make
          - git
          - htop
          - jq
          - unzip
          - gcc
          - openssl-devel
          - libffi-devel
    - name: open firewall port 80
      become: yes
      become_method: sudo
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 80
        jump: ACCEPT
        action: insert
    - name: open firewall port 8000
      become: yes
      become_method: sudo
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 8000
        jump: ACCEPT
        action: insert
    - name: set up pilosa hosts environment variable
      become: yes
      become_method: sudo
      lineinfile:
        path: /etc/profile
        line: "export PILOSA_HOSTS={{ pilosa_hosts }}"
        regexp: "export PILOSA_HOSTS"
      vars:
        pilosa_hosts: "localhost:10101"
- name: install terraform
  hosts: agent
  gather_facts: no
  tasks:
    - name: install terraform binary
      become: yes
      become_method: sudo
      unarchive:
        src: https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip
        dest: /usr/bin
        remote_src: True
