---
- name: basics
  hosts: all
  remote_user: ubuntu
  gather_facts: no
  tasks:
    - name: install software
      become: yes
      become_method: sudo
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
          - make
          - git
          - htop
          - jq
          - unzip
          - python3-pip
          - gcc
    - name: open firewall port 80
      become: yes
      become_method: sudo
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 80
        jump: ACCEPT
        action: insert
    - name: open firewall port 8000
      become: yes
      become_method: sudo
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 8000
        jump: ACCEPT
        action: insert
    - name: install python tools
      become: yes
      become_method: sudo
      pip:
        name: "{{ packages }}"
      vars:
        packages:
          - oci-cli
          - ansible
    - name: set up pilosa hosts environment variable
      become: yes
      become_method: sudo
      lineinfile:
        path: /etc/profile
        line: "export PILOSA_HOSTS={{ pilosa_hosts }}"
        regexp: "export PILOSA_HOSTS"
      vars:
        pilosa_hosts: "localhost:10101"
- name: install terraform
  hosts: all
  remote_user: ubuntu
  gather_facts: no
  tasks:
    - name: install terraform binary
      become: yes
      become_method: sudo
      unarchive:
        src: https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip
        dest: /usr/bin
        remote_src: True
