---
- name: install demo-taxi
  hosts: all
  remote_user: "{{ ansible_user }}"
  gather_facts: no
  tasks:
    - name: pull demo-taxi
      git:
        dest: "/home/{{ ansible_user }}/go/src/github.com/pilosa/demo-taxi"
        repo: "{{ taxi_repo }}"
        version: "{{ taxi_version }}"
        force: true
      vars:
        taxi_repo: https://github.com/pilosa/demo-taxi.git
        taxi_version: master
    - name: install
      command: bash -c 'source /etc/profile.d/go-bin.sh; source /etc/profile.d/go-path.sh; make install-statik; make install'
      args:
        chdir: "/home/{{ ansible_user }}/go/src/github.com/pilosa/demo-taxi"
    - name: update demo-taxi systemd service
      become: yes
      become_method: sudo
      template:
        src: "demo-taxi.service.j2"
        dest: "/etc/systemd/system/demo-taxi.service"
        mode: 0755
      vars:
        pilosa_location: "{{ pilosa_hosts.split(',')[0] }}"
      notify:
        - restart demo-taxi
  handlers:
    - name: restart demo-taxi
      become: yes
      become_method: sudo
      systemd:
        name: demo-taxi
        state: restarted
        daemon_reload: yes
