---
- name: basics
  hosts: agent
  gather_facts: yes
  tasks:
    - name: install software apt
      become: yes
      become_method: sudo
      when: ansible_distribution == "Ubuntu"
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
          - make
          - git
          - htop
          - jq
    - name: install software yum
      become: yes
      become_method: sudo
      when: ansible_distribution == "OracleLinux" or ansible_distribution == "Amazon"
      yum:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
          - make
          - git
          - htop
          - jq
- name: install go
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
  - include_role:
      name: ansible-go
    vars:
      go_tarball: "go1.11.linux-amd64.tar.gz"
      go_tarball_checksum: "sha256:b3fcf280ff86558e0559e185b601c9eade0fd24c900b4c63cd14d1d38613e499"
      go_version_target: "go version go1.11 linux/amd64"
      set_go_path: true
- name: install pdk
  hosts: agent
  gather_facts: no
  tasks:
    - name: pull pdk
      git:
        dest: "/home/{{ ansible_user }}/go/src/github.com/pilosa/pdk"
        repo: "{{ pdk_repo }}"
        version: "{{ pdk_version }}"
      vars:
        pdk_repo: https://github.com/pilosa/pdk.git
        pdk_version: master
    - name: install pdk
      command: bash -c 'source /etc/profile.d/go-bin.sh; source /etc/profile.d/go-path.sh; make install'
      args:
        chdir: "/home/{{ ansible_user }}/go/src/github.com/pilosa/pdk"
- name: install tools
  hosts: agent
  gather_facts: no
  tasks:
    - name: pull tools
      git:
        dest: "/home/{{ ansible_user }}/go/src/github.com/pilosa/tools"
        repo: http://github.com/pilosa/tools.git
    - name: install tools
      command: bash -c 'source /etc/profile.d/go-bin.sh; source /etc/profile.d/go-path.sh; make install'
      args:
        chdir: "/home/{{ ansible_user }}/go/src/github.com/pilosa/tools"
