---
- name: debug a thing
  debug:
    msg: "current host {{ current_hostname }} all hosts {{ zookeeper_hosts }}"
- name: Add apt key for confluent
  apt_key:
    url: https://packages.confluent.io/deb/4.1/archive.key
    state: present
- name: add apt repository for confluent
  apt_repository:
    repo: deb [arch=amd64] https://packages.confluent.io/deb/4.1 stable main
    state: present
    update_cache: yes
- name: install java
  apt:
    name: default-jre-headless
    update_cache: yes
- name: install confluent
  apt:
    name: confluent-platform-oss-2.11
    update_cache: yes
- name: add zookeeper properties
  template:
    src: zookeeper.properties.j2
    dest: /etc/kafka/zookeeper.properties
    owner: cp-kafka
    group: confluent
    force: yes
- name: add myid file
  template:
    src: myid.j2
    dest: /var/lib/zookeeper/myid
    owner: cp-kafka
    group: confluent
    force: yes
- name: replace brokerid in kafka server properties
  lineinfile:
    path: /etc/kafka/server.properties
    line: "broker.id.generation.enable=true"
    state: present
    regexp: "^broker.id="
- name: Make sure zookeeper is running
  systemd:
    daemon_reload: yes
    enabled: yes
    state: started
    name: confluent-zookeeper
- name: Make sure kafka is running
  systemd:
    enabled: yes
    state: started
    name: confluent-kafka
